version: "3.8"

services:

  backend:
    build: ./Backend
    container_name: ems-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env

  frontend:
    build:
      context: ./Frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_REPORTS_URL: ${VITE_REPORTS_URL}
    container_name: ems-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  reports:
    build: ./reports-service
    container_name: ems-reports
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env