version: "3.8"

services:

  backend:
    image: swapnilthakare86/ems-backend:latest
    container_name: ems-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: emp-data.cpg6iaa4wcf8.ap-south-1.rds.amazonaws.com
      DB_NAME: emp_data
      DB_USER: admin
      DB_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Kolkata

  frontend:
    image: swapnilthakare86/ems-frontend:latest
    container_name: ems-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  reports:
    image: swapnilthakare86/ems-reports:latest
    container_name: ems-reports
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: emp-data.cpg6iaa4wcf8.ap-south-1.rds.amazonaws.com
      DB_NAME: emp_data
      DB_USER: admin
      DB_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Kolkata